// Generated by CoffeeScript 1.8.0
(function() {
  var exports, log4js, logger;

  log4js = require('log4js');

  log4js.configure({
    appenders: [
      {
        type: 'console'
      }, {
        type: 'file',
        filename: './logs/cheese.log',
        category: 'cheese',
        maxLogSize: 200 * 1024 * 1024
      }
    ]
  });

  logger = log4js.getLogger('cheese');

  logger.setLevel('error');

  logger.log4js = log4js;

  exports = module.exports = logger;

}).call(this);
